# train_unsloth.py
# Paste this script into your Google Colab notebook (Runtime -> GPU, e.g. T4 or L4).

import torch
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# 1. Configuration
max_seq_length = 1024 
dtype = None # Auto detection: Float16 for Tesla T4, Bfloat16 for Ampere+
load_in_4bit = True # 4-bit QLoRA loading

# Target model
model_name = "unsloth/Qwen2.5-3B-Instruct-bnb-4bit" 

# 2. Load model & tokenizer
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = model_name,
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# 3. Configure LoRA adapter (Rank=16, Alpha=16)
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
)

# 4. Load dataset
# Upload your lora_dataset.json generated by src/generateLoRAData.js
dataset = load_dataset("json", data_files="lora_dataset.json", split="train")

def format_prompts(examples):
    formatted = []
    for msg_list in examples["messages"]:
        text = tokenizer.apply_chat_template(msg_list, tokenize=False, add_generation_prompt=False)
        formatted.append(text)
    return { "text" : formatted }

dataset = dataset.map(format_prompts, batched=True)

# Train/Eval split (90% train, 10% eval)
split_dataset = dataset.train_test_split(test_size=0.1)
train_set = split_dataset["train"]
eval_set = split_dataset["test"]

# 5. Set up SFTTrainer
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = train_set,
    eval_dataset = eval_set,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60, # ~2-3 epochs on ~300 examples
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

# 6. Execute training
print("Starting LoRA fine-tuning...")
trainer_stats = trainer.train()

# 7. Save PEFT LoRA adapter
print("Saving adapter weights...")
model.save_pretrained_lora("interviewer_lora_adapter")
tokenizer.save_pretrained("interviewer_lora_adapter")

# 8. Export to GGUF format for local Ollama serving
print("Exporting to GGUF (q4_k_m)...")
model.save_pretrained_gguf("interviewer_gguf", tokenizer, quantization_method = "q4_k_m")

print("Export complete! Download the GGUF model and import it into Ollama using `ollama create interviewer -f Modelfile`.")
